__author__ = 'Victor'

#Attributes of the Polygons
CATEGORY_RESTORE = "ABLE_RESTORE"
CATEGORY_NOT_RESTORE = "NOT_ABLE_RESTORE"

REASONS_AGRICULTURE = "AGRICULTURE"
REASONS_HISTORIC = "HISTORIC"
REASONS_SPIRITUAL = "SPIRITUAL"
REASONS_ECOLOGY = "ECOLOGY"
REASONS_LANDSCAPE = "LANDSCAPE"
REASONS_ACCESS_WATER = "WATER"